#! /usr/bin/env bash

# print the initial value to sdout
hyprctl activeworkspace -j | jq '.id'

# for future changes, listen to the socket
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - |
  stdbuf -o0 awk -F '>>|,' -e '/^workspace>>/ {print $2}' -e '/^focusedmon>>/ {print $3}'
